### ISSUE TITLE
Could not determine download strategy for "iterate"

### ISSUE THREAD

**Issue by bvnierop** [CodyReichert/qi#37] opened 2016-12-18 19:27 UTC
I'm attempting to use Qi to install the testing library `nst`. It is in the Qi manifest.

It depends on `org-sampler`, which is not in the Qi manifest but can be found. amongst other places, on [github][1].

`org-sampler`, in turn, depends on `iterate`. `Iterate` is in the Qi manifest. When adding it to my _qi.yaml_, however, I get the following output:

    WARNING: redefining QI-SETUP::QI-DIR in DEFUN
    WARNING: redefining QI-SETUP::FIND-ASDF-FASL in DEFUN
    WARNING: redefining QI-SETUP::ENSURE-ASDF-LOADED in DEFUN
    WARNING: redefining QI-SETUP::PUSH-NEW-TO-REGISTRY in DEFUN
    WARNING: redefining QI-SETUP::LOAD-USER-PACKAGES in DEFUN

    While evaluating the form starting at line 102, column 0
      of #P"/home/bart/.qi/bin/../src/cli.lisp":
    Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                        {1001BB6B93}>:
      Could not determine download strategy for "iterate"

    Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1001BB6B93}>
    0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "Could not determine download strategy for ~S" {100262CBA3}> #<unavailable argument>)
    1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "Could not determine download strategy for ~S" {100262CBA3}>)
    2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "Could not determine download strategy for ~S" {100262CBA3}>)
    3: (ERROR "Could not determine download strategy for ~S" "iterate")
    4: (QI.UTIL:DOWNLOAD-STRATEGY "iterate")
    5: (QI::EXTRACT-DEPENDENCY #<HASH-TABLE :TEST EQUAL :COUNT 1 {100262C5A3}>)
    6: (QI::INSTALL-FROM-QI-FILE #P"/home/bart/repos/cl-aoc-2016/qi.yaml")
    7: (INSTALL "aoc")
    8: (SB-INT:SIMPLE-EVAL-IN-LEXENV (MULTIPLE-VALUE-BIND (OPTIONS) (HANDLER-CASE (HANDLER-BIND ((UNIX-OPTS:UNKNOWN-OPTION #)) (UNIX-OPTS:GET-OPTS)) (UNIX-OPTS:MISSING-ARG (CONDITION) (FORMAT T "[fatal] ~s requires an argument~%" (UNIX-OPTS:OPTION CONDITION))) (UNIX-OPTS:ARG-PARSER-FAILED (CONDITION) (FORMAT T "[fatal] ~s not an argument of ~s~%" (UNIX-OPTS:RAW-ARG CONDITION) (UNIX-OPTS:OPTION CONDITION)))) (WHEN-OPTION (OPTIONS :HELP) (UNIX-OPTS:DESCRIBE :PREFIX "Qi - A simple, open, free package manager for Common Lisp." :SUFFIX "Issues https://github.com/CodyReichert/qi" :USAGE-OF "qi" :ARGS "[Free-Args]")) (WHEN-OPTION (OPTIONS :UPGRADE) (RUN-QI-UPGRADE)) (WHEN-OPTION (OPTIONS :INSTALL) (OPT-INSTALL (GETF OPTIONS :INSTALL))) (WHEN-OPTION (OPTIONS :INSTALL-DEPS) (OPT-INSTALL-DEPS (GETF OPTIONS :INSTALL-DEPS)))) #<NULL-LEXENV>)
    9: (SB-EXT:EVAL-TLF (MULTIPLE-VALUE-BIND (OPTIONS) (HANDLER-CASE (HANDLER-BIND ((UNIX-OPTS:UNKNOWN-OPTION #)) (UNIX-OPTS:GET-OPTS)) (UNIX-OPTS:MISSING-ARG (CONDITION) (FORMAT T "[fatal] ~s requires an argument~%" (UNIX-OPTS:OPTION CONDITION))) (UNIX-OPTS:ARG-PARSER-FAILED (CONDITION) (FORMAT T "[fatal] ~s not an argument of ~s~%" (UNIX-OPTS:RAW-ARG CONDITION) (UNIX-OPTS:OPTION CONDITION)))) (WHEN-OPTION (OPTIONS :HELP) (UNIX-OPTS:DESCRIBE :PREFIX "Qi - A simple, open, free package manager for Common Lisp." :SUFFIX "Issues https://github.com/CodyReichert/qi" :USAGE-OF "qi" :ARGS "[Free-Args]")) (WHEN-OPTION (OPTIONS :UPGRADE) (RUN-QI-UPGRADE)) (WHEN-OPTION (OPTIONS :INSTALL) (OPT-INSTALL (GETF OPTIONS :INSTALL))) (WHEN-OPTION (OPTIONS :INSTALL-DEPS) (OPT-INSTALL-DEPS (GETF OPTIONS :INSTALL-DEPS)))) 12 NIL)
    10: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (MULTIPLE-VALUE-BIND (OPTIONS) (HANDLER-CASE (HANDLER-BIND ((UNIX-OPTS:UNKNOWN-OPTION #)) (UNIX-OPTS:GET-OPTS)) (UNIX-OPTS:MISSING-ARG (CONDITION) (FORMAT T "[fatal] ~s requires an argument~%" (UNIX-OPTS:OPTION CONDITION))) (UNIX-OPTS:ARG-PARSER-FAILED (CONDITION) (FORMAT T "[fatal] ~s not an argument of ~s~%" (UNIX-OPTS:RAW-ARG CONDITION) (UNIX-OPTS:OPTION CONDITION)))) (WHEN-OPTION (OPTIONS :HELP) (UNIX-OPTS:DESCRIBE :PREFIX "Qi - A simple, open, free package manager for Common Lisp." :SUFFIX "Issues https://github.com/CodyReichert/qi" :USAGE-OF "qi" :ARGS "[Free-Args]")) (WHEN-OPTION (OPTIONS :UPGRADE) (RUN-QI-UPGRADE)) (WHEN-OPTION (OPTIONS :INSTALL) (OPT-INSTALL (GETF OPTIONS :INSTALL))) (WHEN-OPTION (OPTIONS :INSTALL-DEPS) (OPT-INSTALL-DEPS (GETF OPTIONS :INSTALL-DEPS)))) 12)
    11: ((LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) (MULTIPLE-VALUE-BIND (OPTIONS) (HANDLER-CASE (HANDLER-BIND ((UNIX-OPTS:UNKNOWN-OPTION #)) (UNIX-OPTS:GET-OPTS)) (UNIX-OPTS:MISSING-ARG (CONDITION) (FORMAT T "[fatal] ~s requires an argument~%" (UNIX-OPTS:OPTION CONDITION))) (UNIX-OPTS:ARG-PARSER-FAILED (CONDITION) (FORMAT T "[fatal] ~s not an argument of ~s~%" (UNIX-OPTS:RAW-ARG CONDITION) (UNIX-OPTS:OPTION CONDITION)))) (WHEN-OPTION (OPTIONS :HELP) (UNIX-OPTS:DESCRIBE :PREFIX "Qi - A simple, open, free package manager for Common Lisp." :SUFFIX "Issues https://github.com/CodyReichert/qi" :USAGE-OF "qi" :ARGS "[Free-Args]")) (WHEN-OPTION (OPTIONS :UPGRADE) (RUN-QI-UPGRADE)) (WHEN-OPTION (OPTIONS :INSTALL) (OPT-INSTALL (GETF OPTIONS :INSTALL))) (WHEN-OPTION (OPTIONS :INSTALL-DEPS) (OPT-INSTALL-DEPS (GETF OPTIONS :INSTALL-DEPS)))) :CURRENT-INDEX 12)
    12: (SB-C::%DO-FORMS-FROM-INFO #<CLOSURE (LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) {1004AB8D4B}> #<SB-C::SOURCE-INFO {1004AB8D03}> SB-C::INPUT-ERROR-IN-LOAD)
    13: (SB-INT:LOAD-AS-SOURCE #<SB-INT:FORM-TRACKING-STREAM for "file /home/bart/.qi/src/cli.lisp" {1004AB6683}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
    14: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<SB-INT:FORM-TRACKING-STREAM for "file /home/bart/.qi/src/cli.lisp" {1004AB6683}> NIL)
    15: (LOAD #P"/home/bart/.qi/bin/../src/cli.lisp" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
    16: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:LOAD . "/home/bart/.qi/bin/../init.lisp") (:LOAD . "/home/bart/.qi/bin/../src/cli.lisp") (:QUIT)))
    17: (SB-IMPL::TOPLEVEL-INIT)
    18: ((FLET #:WITHOUT-INTERRUPTS-BODY-86 :IN SB-EXT:SAVE-LISP-AND-DIE))
    19: ((LABELS SB-IMPL::RESTART-LISP :IN SB-EXT:SAVE-LISP-AND-DIE))

    unhandled condition in --disable-debugger mode, quitting

  [1]: https://github.com/jphmrst/cl-org-sampler

**Comment by CodyReichert** [comment] 2016-12-18 22:06
Hey @bvnierop -- thanks for the report. It looks like this is because `iterate` didn't have a valid URL in the manifest.

I just fixed that, and I also went ahead and added `org-sampler` to the manifest also.

It _should_ be able to find a download strategy for `iterate` now. Would you mind giving it another shot when you get a chance?

**Comment by dunn** [comment] 2016-12-18 22:21
Currently `install-transitive-dependencies` doesn't know to check the `qi.yaml` if it can't find the package in the manifest; that might be a regression I introduced.  But I'm working on a fix.

**Comment by bvnierop** [comment] 2016-12-19 05:34
Thanks for the quick replies and fix @CodyReichert  and @dunn.

Unfortunately, `iterate-current.tar.gz` is broken, as are older versions. An unbroken version is on [darcs][1], which is where Quicklisp gets it from.

I guess this results in the following:
- A feature request for Qi to support Darcs
- Taking the broken version of `iterate` out of the manifest
- (and for myself) Host a tar of the darcs version of `iterate` somewhere so that I can use it

  [1]: https://common-lisp.net/project/iterate/darcs/iterate/

**Comment by bvnierop** [comment] 2016-12-19 19:13
Small update, I've tested with the following `qi.yaml`:

    name: aoc
    packages:
        - name: iterate
          url: https://my-self-hosted-copy-of.iter/iterate.tar.gz
        - name: nst

And that installs correctly.

**Comment by dunn** [comment] 2017-06-04 01:10
Since you've got a workaround, and since this just depends on a new stable release of iterate, I'm going to close this issue.

**Closed as completed by dunn** 2017-06-04 01:10 UTC
